# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  sohatnotebookapi:
    image: sohatnotebookapi
    build:
      context: .
      dockerfile: src/sohatNotebook.Api/Dockerfile
    ports:
      - 80:80
